config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    root to: 'homes#top'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :items, except: [:destroy]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
  end
  scope module: :public do
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resource :customers, only: [:show, :edit, :update]
  end
  scope module: :public do
    resources :items, only: [:index, :show]
  end
  scope module: :public do
    resources :addresses, except: [:new, :show]
  end
  scope module: :public do
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  scope module: :public do
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete', as: 'complete'
    resources :orders, only: [:new, :index, :create, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

    belongs_to :customer

    def order_address
      "〒" + postal_code + " " + address + "　" + name
    end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

    belongs_to :customer
    belongs_to :item

    def subtotal
        item.with_tax_price*amount
    end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def name
    last_name +  first_name
  end

  def name_s
    last_name + "　" + first_name
  end

  def name_kana
    last_name_kana + first_name_kana
  end

  def name_kana_s
    last_name_kana + "　" + first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    belongs_to :genre, optional: true

    has_one_attached :image

    def get_image(width, height)
        unless image.attached?
          file_path = Rails.root.join('app/assets/images/no_image.jpg')
          image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
        end
        image.variant(resize_to_limit: [width, height]).processed
    end

    def with_tax_price
        (price*1.1).floor
    end

end

app/models/order.rb
class Order < ApplicationRecord

    has_many :order_details, dependent: :destroy
    belongs_to :customer

    enum payment: { credit_card: 0, transfer: 1}
    enum status: { waiting: 0, paid_up: 1, making: 2, preparing: 3, shipped: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

    belongs_to :item
    belongs_to :order
    
    enum making_status: { impossble: 0, waiting: 1, making: 2, finished: 3}
    
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer =  Customer.find(params[:id])
  end

  def edit
    @customer =  Customer.find(params[:id])
  end

  def update
    if @customer =  Customer.find(params[:id])
      @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :last_name_kana, :first_name, :first_name_kana,
    :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルが追加されました。"
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルが更新されました。"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @total = 0
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_order_path(@order.id)
    else
      render :show
    end
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h5 class="my-4 col-md-4 py-1 text-center"><%= @customer.last_name + @customer.first_name %><span>さんの</span>会員情報編集</h5>

      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch, local: true do |f| %>
        <div class="form-group">
          <table class="table table-borderless">
            <tr>
              <td class="col-3">会員ID</td>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <td><%= f.label :name, "氏名" %></td>
              <td>
                <%= f.text_field :last_name %>
                <%= f.text_field :first_name %>
              </td>
            </tr>
            <tr>
              <td><%= f.label :name_kana, "ふりがな" %></td>
              <td>
                <%= f.text_field :last_name_kana %>
                <%= f.text_field :first_name_kana %>
              </td>
            </tr>
            <tr>
              <td><%= f.label :postal_code, "郵便番号" %></td>
              <td><%= f.text_field :postal_code %></td>
            </tr>
            <tr>
              <td><%= f.label :address, "住所" %></td>
              <td><%= f.text_field :address, class: "col-8" %></td>
            </tr>
            <tr>
              <td><%= f.label :telephone_number, "電話番号" %></td>
              <td><%= f.text_field :telephone_number %></td>
            </tr>
            <tr>
              <td><%= f.label :email, "メールアドレス" %></td>
              <td><%= f.text_field :email %></td>
            </tr>
            <tr>
              <td><%= f.label :is_active, "会員ステータス" %></td>
              <td>
                <div class="radio_button">
                  <%= f.radio_button :is_active, true %>
                  <%= f.label :is_active, "有効", value: true %>
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active, "退会", value: false %>
                </div>
              </td>
            </tr>
          </table>
        </div>

        <div class="form-group">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h5 class="mt-4 mb-3 col-md-2 py-1 text-center">会員一覧</h5>

      <table class="table table-sm col-md-10 mx-auto">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.name, admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
            <td>
              <%if customer.is_active == true %>
                有効
              <% else %>
                退会
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>

      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 pb-5">
      <h5 class="my-4 col-md-5 py-1 text-center"><%= @customer.name %><span>さんの</span>会員詳細</h5>

      <table class="table table-borderless table-sm">
        <tr>
          <td class="col-3">会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.name_s %></td>
        </tr>
        <tr>
          <td>ふりがな</td>
          <td><%= @customer.name_kana_s %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <% if @customer.is_active == true %>
              有効
            <% else %>
              退会
            <% end %>
          </td>
        </tr>
      </table>

      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success offset-md-3" %>
    </div>
  </div>
</div>