config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    root to: 'homes#top'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :items, except: [:destroy]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
  end
  scope module: :public do
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resource :customers, only: [:show, :edit, :update]
  end
  scope module: :public do
    resources :items, only: [:index, :show]
  end
  scope module: :public do
    resources :addresses, except: [:new, :show]
  end
  scope module: :public do
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  scope module: :public do
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete', as: 'complete'
    resources :orders, only: [:new, :index, :create, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

    belongs_to :customer

    def order_address
      "〒" + postal_code + " " + address + "　" + name
    end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

    belongs_to :customer
    belongs_to :item

    def subtotal
        item.with_tax_price*amount
    end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def name
    last_name +  first_name
  end

  def name_s
    last_name + "　" + first_name
  end

  def name_kana
    last_name_kana + first_name_kana
  end

  def name_kana_s
    last_name_kana + "　" + first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    belongs_to :genre, optional: true

    has_one_attached :image

    def get_image(width, height)
        unless image.attached?
          file_path = Rails.root.join('app/assets/images/no_image.jpg')
          image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
        end
        image.variant(resize_to_limit: [width, height]).processed
    end

    def with_tax_price
        (price*1.1).floor
    end

end

app/models/order.rb
class Order < ApplicationRecord

    has_many :order_details, dependent: :destroy
    belongs_to :customer

    enum payment: { credit_card: 0, transfer: 1}
    enum status: { waiting: 0, paid_up: 1, making: 2, preparing: 3, shipped: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

    belongs_to :item
    belongs_to :order
    
    enum making_status: { impossble: 0, waiting: 1, making: 2, finished: 3}
    
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルが追加されました。"
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルが更新されました。"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @total = 0
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_order_path(@order.id)
    else
      render :show
    end
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
    <div class="row">
        <div class="">
            <h5 class="bg-light">ジャンル編集</h5>

            <div class="form-group">
                <%= form_with model: @genre, url: admin_genres_path(@genre.id), method: :patch, local: true do |f| %>
                    <%= f.label :name, "ジャンル名" %>
                    <%= f.text_field :name %>
                    <%= f.submit "変更を保存", class: "btn btn-success btn-sm px-3" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="">
      <h5>ジャンル一覧・追加</h5>

      <div class="form-group">
        <%= form_with model: @genre, url: "/admin/genres", method: :post, local: true do |f| %>
          <%= f.label :name, "ジャンル名" %>
          <%= f.text_field :name %>
          <%= f.submit "新規登録", class: "btn btn-success btn-sm px-4" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="">
      <table class="table table-sm">
        <tr>
          <th colspan="2" class="table-active">ジャンル</th>
        </tr>
        <% @genres.each do |genre| %>
          <tr>
            <td>
              <%= genre.name %>
            </td>
            <td>
              <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success btn-sm px-4" %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mb-5">
      <h5 class="my-4 col-md-2 py-1 text-center">注文履歴一覧</h5>

      <table class="table table-sm">
        <tr class="table-active">
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>

        <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order.id) %>
            </td>
            <td><%= link_to order.customer.name, admin_customer_path(order.customer_id) %></td>
            <td><%= order.order_details.all.sum(:amount) %></td>
            <td><%= order.status_i18n %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <h5 class="mt-4 col-md-2 py-1 text-center">商品編集</h5>

      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch, local: true do |f| %>
        <div class="form-group">
          <table class="table table-borderless col-8">
            <tr>
              <td class="col-3"><%= f.label :image, "商品画像" %></td>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <td><%= f.label :name, "商品名" %></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= f.label :introduction, "商品説明" %></td>
              <td><%= f.text_area :introduction %></td>
            </tr>
            <tr>
              <td><%= f.label :genre_id, "ジャンル" %></td>
              <td><%= f.collection_select(:genre_id, @genres, :id, :name) %></td>
            </tr>
            <tr>
              <td><%= f.label :price, "税抜価格" %></td>
              <td><%= f.text_field :price %> 円</td>
            </tr>
            <tr>
              <td><%= f.label :is_active, "販売ステータス" %></td>
              <td>
                <div class="radio_button">
                  <%= f.radio_button :is_active, true %>
                  <%= f.label :is_active, "販売中", value: true %>
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active, "販売停止中", value: false %>
                </div>
              </td>
            </tr>
          </table>
        </div>

        <div class="form-group">
          <%= f.submit "変更を保存", class: "btn btn-success px-4" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-11 mx-auto mb-5 pb-3">
      <h5 class="offset-md-1 mt-4 text-center col-2">商品一覧</h5>
      <p class="col-1 offset-md-11"><%= link_to "＋", new_admin_item_path, class: "btn btn-light btn-sm" %></p>

      <table class="table table-borderless table-sm">
        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <% @items.each do |item| %>
          <tr>
            <td><%= item.id.to_i %></td>
            <td><%= link_to item.name, admin_item_path(item.id) %></td>
            <td><%= item.price %></td>
            <td><%= item.genre.name %></td>
            <td>
              <% if item.is_active == true %>
                <strong class="text-success">販売中</strong>
              <% else %>
                <strong class="text-secondary">販売停止中</strong>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>

      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h3><%= @item.errors.count %>errors prohibited this obj form being saved:</h3>
          <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h5 class="mt-4 col-md-2 py-1 text-center">商品新規登録</h5>

      <%= form_with model: @item, url: "/admin/items", method: :post, local: true do |f| %>
        <div class="form-group">
          <table class="table table-borderless">
            <tr>
              <td><%= f.label :image, "商品画像" %></td>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <td><%= f.label :name, "商品名" %></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= f.label :introduction, "商品説明" %></td>
              <td><%= f.text_area :introduction %></td>
            </tr>
            <tr>
              <td><%= f.label :genre_id, "ジャンル" %></td>
              <td><%= f.collection_select(:genre_id, @genres, :id, :name) %></td>
            </tr>
            <tr>
              <td><%= f.label :price, "税抜価格" %></td>
              <td><%= f.text_field :price %> 円</td>
            </tr>
            <tr>
              <td><%= f.label :is_active, "販売ステータス" %></td>
              <td>
                <div class="radio_button">
                  <%= f.radio_button :is_active, true %>
                  <%= f.label :is_active, "販売中", value: true %>
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active, "販売停止中", value: false %>
                </div>
              </td>
            </tr>
          </table>
        </div>

        <div class="form-group">
          <%= f.submit "新規登録", class: "btn btn-success btn-sm px-4" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container mx-auto">
  <div container="row">
    <div class="col-md-8">
      <h5 class="mt-4 col-md-2 py-1 text-center offset-1">商品詳細</h5>
    </div>

    <div class="row">
      <div class="col-3 offset-2">
        <%= image_tag @item.get_image(280, 250) %>
      </div>

      <div class="col-6 ml-1 mb-5">
        <table class="table table-borderless">
          <tr>
            <td class="col-4">商品名</td>
            <td><%= @item.name %></td>
          </tr>

          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>

          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>

          <tr>
            <td>
              税込価格<br>
              (税抜価格)
            </td>
            <td>
              <%= (@item.price*1.1).floor %>円
              (<%= @item.price %>円)
            </td>
          </tr>

          <tr>
            <td>販売ステータス</td>
            <td>
              <% if @item.is_active == true %>
                販売中
              <% else %>
                販売停止中
              <% end %>
            </td>
          </tr>
        </table>

        <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success px-4" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h5 class="mt-4 col-md-2 py-1 text-center">注文履歴詳細</h5>

            <table class="table table-borderless">
                <tr>
                    <th>購入者</th>
                    <td><%= @order.customer.name %></td>
                </tr>
                <tr>
                    <th>注文日</th>
                    <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
                </tr>
                <tr>
                    <th>配送先</th>
                    <td>
                        〒<%= @order.postal_code %>
                        <%= @order.address %><br>
                        <%= @order.name %>
                    </td>
                </tr>
                <tr>
                    <th>支払方法</th>
                    <td><%= @order.payment_i18n %></td>
                </tr>
                <tr>
                    <th>注文ステータス</th>
                    <td>
                        <%=form_with model: @order, url: admin_order_path(@order.id), method: :patch, local: true do |f| %>
                            <%= f.select :status, Order.statuses_i18n.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]}, class: "form-control" %>
                            <%= f.submit "更新", class: "btn btn-success btn-sm" %>
                        <% end %>
                    </td>
                </tr>
            </table>

            <table class="table table-sm">
                <tr class="table-active">
                    <td>商品名</td>
                    <td>単価(税込)</td>
                    <td>数量</td>
                    <td>小計</td>
                    <td>製作ステータス</td>
                </tr>
                <% @order.order_details.each do |order_detail| %>
                    <tr>
                        <td><%= order_detail.item.name %></td>
                        <td><%= order_detail.price %></td>
                        <td><%= order_detail.amount %></td>
                        <td><%= order_detail.price * order_detail.amount %></td>
                        <td>
                            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch, local: true do |f| %>
                                <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"),k]}, class: "form-control" %>
                                <%= f.submit "更新", class: "btn btn-success btn-sm" %>
                            <% end %>
                        </td>
                    </tr>
                    <% @total += (order_detail.price * order_detail.amount) %>
                <% end %>
            </table>

            <table class="table table-borderless table-sm">
                <tr>
                    <th>商品合計</th>
                    <td><%= @total %></td>
                </tr>
                <tr>
                    <th>送料</th>
                    <td><%= @order.postage %></td>
                </tr>
                <tr>
                    <th>請求金額合計</th>
                    <td><%= @order.total_price %></td>
                </tr>
            </table>
        </div>
    </div>
</div>