config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    root to: 'homes#top'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :items, except: [:destroy]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
  end
  scope module: :public do
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resource :customers, only: [:show, :edit, :update]
  end
  scope module: :public do
    resources :items, only: [:index, :show]
  end
  scope module: :public do
    resources :addresses, except: [:new, :show]
  end
  scope module: :public do
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  scope module: :public do
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete', as: 'complete'
    resources :orders, only: [:new, :index, :create, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

    belongs_to :customer

    def order_address
      "〒" + postal_code + " " + address + "　" + name
    end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

    belongs_to :customer
    belongs_to :item

    def subtotal
        item.with_tax_price*amount
    end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def name
    last_name +  first_name
  end

  def name_s
    last_name + "　" + first_name
  end

  def name_kana
    last_name_kana + first_name_kana
  end

  def name_kana_s
    last_name_kana + "　" + first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    belongs_to :genre, optional: true

    has_one_attached :image

    def get_image(width, height)
        unless image.attached?
          file_path = Rails.root.join('app/assets/images/no_image.jpg')
          image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
        end
        image.variant(resize_to_limit: [width, height]).processed
    end

    def with_tax_price
        (price*1.1).floor
    end

end

app/models/order.rb
class Order < ApplicationRecord

    has_many :order_details, dependent: :destroy
    belongs_to :customer

    enum payment: { credit_card: 0, transfer: 1}
    enum status: { waiting: 0, paid_up: 1, making: 2, preparing: 3, shipped: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

    belongs_to :item
    belongs_to :order
    
    enum making_status: { impossble: 0, waiting: 1, making: 2, finished: 3}
    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのCAKE</title>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light border">
        <div class="container mx-0">
          <a class="navbar-brand pt-3" href="/">
            <%= image_tag "Logokako-shadow-lGFrMffM5042jPdp", :size => "260x50" %>
          </a>
          <% if customer_signed_in? %>
            <p>ようこそ、<%= current_customer.last_name %>さん！</p>
          <% elsif admin_signed_in? %>
            <p>管理者ログイン中</p>
          <% end %>
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li>
                <%= link_to "マイページ", customers_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-2 ml-5" %>
              </li>
              <li>
                <%= link_to "商品一覧", items_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-3 ml-5" %>
              </li>
              <li>
                <%= link_to "カート", cart_items_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-3 ml-5" %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-2 ml-5" %>
              </li>
            <% elsif admin_signed_in? %>
              <li>
                <%= link_to "商品一覧", admin_items_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-3 ml-4" %>
              </li>
              <li>
                <%= link_to "会員一覧", admin_customers_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-3 ml-4" %>
              </li>
              <li>
                <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-2 ml-4" %>
              </li>
              <li>
                <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-2 ml-4" %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-2 ml-4" %>
              </li>
            <% else %>
              <li>
                <%= link_to "About", about_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-4 ml-5" %>
              </li>
              <li>
                <%= link_to "商品一覧", items_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-3 ml-5" %>
              </li>
              <li>
                <%= link_to "新規登録", new_customer_registration_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-3 ml-5" %>
              </li>
              <li>
                <%= link_to "ログイン", new_customer_session_path, class: "nav-link text-dark btn btn-outline-secondary btn-sm px-3 ml-5" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>


    <fooder>
      <div class="container border col-12 mb-5">
        <div class="row">
          <div class="mx-auto">

          </div>
        </div>
      </div>
    </fooder>
  </body>
</html>